ユーザー登録機能（ログイン・ログアウト機能込み）の実装
yusukekaneko/twitter_clone pull request #1
Opened 2021-08-12 11:58 UTC by yusukekaneko

ユーザー登録機能（ログイン・ログアウト機能込み）を実装致しました。
ご確認の程よろしくお願い致します。

2021-08-13 13:23 UTC, TonkyH commented on .gitignore
> +.DS_Store
空行追加

2021-08-13 13:23 UTC, TonkyH commented on apps/registration/forms.py
> +    return False
空行追加

2021-08-13 13:23 UTC, TonkyH commented on apps/registration/static/registration/css/registration.css
> +}
空行追加

2021-08-13 13:23 UTC, TonkyH commented on templates/registration/activate.html
> +{% endblock %}
空行追加

2021-08-13 13:23 UTC, TonkyH commented on templates/registration/base.html
> +</html>
空行追加

2021-08-13 13:23 UTC, TonkyH commented on templates/registration/index.html
> +{% endblock %}
空行追加

2021-08-13 13:23 UTC, TonkyH commented on templates/registration/login.html
> +{% endblock %}
空行追加

2021-08-13 13:23 UTC, TonkyH commented on templates/registration/signup.html
> +{% endblock %}
空行追加

2021-08-13 13:23 UTC, TonkyH commented on twitter_clone/urls.py
> +]
空行追加

2021-08-13 13:23 UTC, TonkyH commented on apps/registration/forms.py
> +from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
アルファベット順の方が見やすいと思います

2021-08-13 13:23 UTC, Atiisann commented on apps/registration/views.py
> +from .forms import activate_user
importの並び替え

2021-08-13 13:23 UTC, Atiisann commented on apps/registration/views.py
> +class ActivateView(TemplateView):
これはいつ使われてますか？？

2021-08-13 13:25 UTC, Atiisann commented
動作確認したスクショを貼って欲しいです🙏

2021-08-13 13:29 UTC, Atiisann commented
あと、ディレクトリの構造がどうなってるか確認だけさせてもらってもいいですか？？
スクショ貼ってもらえたら嬉しいです

2021-08-14 02:02 UTC, yusukekaneko commented on .gitignore
> +.DS_Store
空行追加とは具体的にどういうことなのでしょうか？（以下同様）

2021-08-14 02:04 UTC, yusukekaneko commented
<img width="1114" alt="ログイン画面" src="https://user-images.githubusercontent.com/81793599/129431215-cd0a2087-2751-4eda-901e-2ac6987dbe7c.PNG">
<img width="1108" alt="登録画面" src="https://user-images.githubusercontent.com/81793599/129431217-4e78e70a-9189-44ec-aed7-8300f9ac1b7f.PNG">
<img width="1110" alt="ログアウト画面" src="https://user-images.githubusercontent.com/81793599/129431219-0e408e72-3f7b-45b6-96be-e39b66a8a76a.PNG">

2021-08-14 02:24 UTC, yusukekaneko commented
ログイン画面
<img width="1114" alt="ログイン画面" src="https://user-images.githubusercontent.com/81793599/129431599-7b73105c-590a-40e9-8c86-51da8ee5fd0b.PNG">

登録画面（新規登録リンクから遷移）
<img width="1108" alt="登録画面" src="https://user-images.githubusercontent.com/81793599/129431613-8cc290b4-d237-4678-baf9-18da55f796e0.PNG">

ログアウト画面
<img width="1110" alt="ログアウト画面" src="https://user-images.githubusercontent.com/81793599/129431616-e4d41b23-5fde-43b8-868a-9c6eca1ba412.PNG">

2021-08-14 02:25 UTC, yusukekaneko commented
ディレクトリの構造
<img width="708" alt="ディレクトリ" src="https://user-images.githubusercontent.com/81793599/129431639-49930c0c-0655-4ea9-a520-90d3545f50bb.PNG">

2021-08-14 02:45 UTC, Atiisann commented on .gitignore
> +.DS_Store
EOFを追加してくださいという意味でした

- https://ja.wikipedia.org/wiki/End_Of_File
- https://qiita.com/facultyoflaw11/items/14c16f1b624ffd2f383c

2021-08-14 02:46 UTC, yusukekaneko commented on .gitignore
> +.DS_Store
承知しました。

2021-08-14 02:53 UTC, Atiisann commented on twitter_clone/urls.py
> +    path('activate/<uidb64>/<token>/', views.ActivateView.as_view(), name='activate'),
ディレクトリ構造を確認しました

サインアップ周りは`registoration`アプリが管理した方がいいと思うので、
`registoration/urls.py`に移植した方がいいと思います

あとでゴチャゴチャになってしまうので、、

2021-08-14 03:02 UTC, Atiisann commented on apps/registration/forms.py
> +from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
その他、importの順番についての参考資料！
https://pep8-ja.readthedocs.io/ja/latest/#import

2021-08-18 11:56 UTC, Atiisann requested changes
修正おねがいします！

2021-08-18 11:56 UTC, Atiisann commented on apps/registration/tests.py
> +
EOF追加

2021-08-18 12:35 UTC, yusukekaneko commented
先程、誤ってAtiisannからのコメントを1つ削除してしまいました申し訳ありません。

2021-08-19 06:22 UTC, fumiharun11 commented on apps/registration/tests.py
> +from django.contrib.auth.models import User
`get_user_model`関数でUserクラスを取得しているので不要なimportかな？

2021-08-19 06:22 UTC, fumiharun11 commented on apps/registration/urls.py
> +index_view = TemplateView.as_view(template_name="registration/index.html")
urlのpath定義モジュールにviewの定義をしている理由はありますか？
理由がなければviews.pyで`TemplateView`と`LoginRequiredMixin`を継承したクラスベースビューで定義しましょう。
理由があれば、返信をお願いします。

2021-08-19 10:56 UTC, fumiharun11 approved these changes
LGTM
![](https://media.giphy.com/media/3o7abB06u9bNzA8lu8/giphy.gif)

2021-08-19 11:07 UTC, merged