ツイート機能の実装
yusukekaneko/twitter_clone pull request #2
Opened 2021-09-04 08:58 UTC by yusukekaneko

ツイート機能を実装致しました。
ご確認の程よろしくお願い致します。

2021-09-05 03:35 UTC, Atiisann requested changes

2021-09-05 03:35 UTC, Atiisann commented on apps/registration/tests.py
> -        self.assertEquals(post_response.status_code, 200)
失敗時のステータスコード確認してもらってもいいですか？？
おそらく400が返されているかなと思います

他のテストケースも同様に確認お願いします

2021-09-05 03:35 UTC, Atiisann commented on apps/registration/urls.py
空行２つください
https://pep8-ja.readthedocs.io/ja/latest/#id12

2021-09-05 03:35 UTC, Atiisann commented on apps/registration/urls.py
逆にここは空行１つでいいです！

2021-09-05 03:35 UTC, Atiisann commented on apps/tweet/admin.py
> +
空行２つにしてください

2021-09-05 03:35 UTC, Atiisann commented on apps/tweet/views.py
> +       return Post.objects.exclude(user=self.request.user)
ホーム画面？で自分のツイートを表示しないことに理由はありますか？？
Twitterだと、自分のツイートも表示されていると思うので少し違和感を感じました！

2021-09-05 04:47 UTC, yusukekaneko commented on apps/registration/tests.py
> -        self.assertEquals(post_response.status_code, 200)
追加してテストしたところ、ステータスコードが400ではなく200であるとのエラーが返ってきました。
ちなみに、上記のコードを今回のプルリクエストで削除した理由は、ステータスコードが200であるテストは検証する必要がないと考えたからです。

2021-09-05 10:34 UTC, Atiisann commented
LGTM

2021-09-07 04:16 UTC, fumiharun11 reviewed
全体的に良いと思います。
補足のコメントについては確認後、必要があれば対応をお願いします。
補足でないコメントについては確認後、コメントへの返信+必要があれば対応をお願いします。

2021-09-07 04:16 UTC, fumiharun11 commented on apps/tweet/models.py
> +   user = models.ForeignKey(User, on_delete=models.CASCADE)
補足: `created_by`や`author`などのフィールド[カラム]名にしておくと紐付けられている`User`の役割が明確になるので、命名時の参考にしてください。

2021-09-07 04:16 UTC, fumiharun11 commented on apps/tweet/views.py
> +       post = Post.objects.get(pk=pk)
DB上にレコードが存在しない場合に50x系のエラーが出てしまう懸念があるのだけど、その点についてカバー出来ていますか？
出来ていない場合は、ページ遷移ではなくURLから直接アクセスされた場合を考慮して`get_object_or_404`を利用するのが良いと思います。

2021-09-07 04:16 UTC, fumiharun11 commented on apps/registration/tests.py
> -        self.assertEquals(post_response.status_code, 200)
補足: リクエスト自体は処理出来ているため、レスポンスのステータスコードが200になることは問題ないと思います。
テストについても目的に合わせたassertionを置く方針で良いと思うので、フォームに含まれた値がinvalidな場合のテストでは消して問題無いと考えます。

2021-09-07 06:03 UTC, yusukekaneko commented on apps/tweet/views.py
> +       post = Post.objects.get(pk=pk)
修正しました。

2021-09-07 06:04 UTC, yusukekaneko commented on apps/registration/tests.py
> -        self.assertEquals(post_response.status_code, 200)
了解しました。

2021-09-07 06:04 UTC, yusukekaneko commented on apps/tweet/models.py
> +   user = models.ForeignKey(User, on_delete=models.CASCADE)
了解しました。

2021-09-07 06:06 UTC, fumiharun11 approved these changes
![](https://media.tumblr.com/b999d6fa94d40545edb2dac70623e070/tumblr_inline_n2ztfg6zr01qaxsyz.gif)

2021-09-07 06:06 UTC, merged