フォロー機能の実装
yusukekaneko/twitter_clone pull request #3
Opened 2021-09-12 11:32 UTC by yusukekaneko

フォロー機能を実装致しました。
ご確認の程よろしくお願い致します。

2021-09-13 09:39 UTC, Atiisann requested changes

2021-09-13 09:39 UTC, TonkyH commented on apps/tweet/tests.py
> +        time.sleep(0.3)
0.3秒処理を一時停止する意図はなんでしょうか？？

2021-09-13 09:39 UTC, TonkyH commented on apps/tweet/urls.py
> +"""
```python
"""
app_name = 'apps.tweet'
"""
```
こうした理由はありますか？？？

2021-09-13 09:39 UTC, Atiisann commented on apps/users/views.py
> +      request_user_following_list = User.objects.filter(id__in=request_user_following_data)
コードを見た感じ、`UserProfile`はpathに含まれる`username`を持つユーザーのプロフィール？情報を取得するviewだと思うのですが、
ここで、リクエストしてきたユーザーの情報を返す理由はなんでしょうか？？

2021-09-13 09:39 UTC, Atiisann commented on apps/users/views.py
> +        elif following in follower[0].following.all():
```python
follower[0].following.filter(pk=self.kwargs['pk']).exists()
```
みたいな感じで`in`を使わずに存在判定できませんでしたか？？

2021-09-13 09:39 UTC, Atiisann commented on apps/users/views.py
> +            follower[0].following.add(following)
`add`したあと、`save`を実行しなくても
変更が反映されていましたか？？

2021-09-13 09:39 UTC, Atiisann commented on apps/users/views.py
> +class FollowInUserProfile(FollowBase):
`FollowInUserProfileView`にしない理由はありますか？？
他の部分では最後に`View`がついています

2021-09-13 09:40 UTC, Atiisann commented
動作確認した結果をスクショして貼っておいてください🙇‍♂️

2021-09-13 10:34 UTC, yusukekaneko commented on apps/tweet/urls.py
> +"""
usersアプリにtweetアプリのurlをincludeするというルーティングの変更を加えた為、このようにしました。

2021-09-13 10:39 UTC, yusukekaneko commented on apps/users/views.py
> +      request_user_following_list = User.objects.filter(id__in=request_user_following_data)
あるユーザーのプロフィールをリクエストした際に、リクエストユーザーがその人をfollowしていた場合はFollowing、そうでない場合はFollowとhtml側で表示する為に、リクエストユーザーのfollowing情報を返しています。

2021-09-13 11:32 UTC, yusukekaneko commented on apps/tweet/tests.py
> +        time.sleep(0.3)
ここでは作成されたツイートがすべて表示され、且つそれらが新しい順であるかをテストしているのですが、以前にこのテストを数回実行した際に、（本来通るはずのテストで）稀にツイートの順番が異なるというエラーが生じていました。そこで、そのエラーの解決策としてtime.sleepでツイートの順番を確定させるようにしました。

2021-09-13 11:36 UTC, yusukekaneko commented on apps/users/views.py
> +class FollowInUserProfile(FollowBase):
他のtemplateを返すものとは違い、ここはあくまでfollow機能であり、同じページにredirectすることでfollow情報を更新する為Viewはつけませんでした。

2021-09-13 12:03 UTC, yusukekaneko commented
ホーム画面
・自分も含めた全ユーザーのツイートが新しい順で表示される
・今回はadmin1アカウントでログイン（以下同様）
<img width="1115" alt="ホーム画面" src="https://user-images.githubusercontent.com/81793599/133078077-551c5b51-dfa6-465b-9db1-0a956ca9f067.PNG">

ユーザープロフィール画面１
・各ツイートの投稿者の名前をクリックすることで指定のユーザープロフィール画面へ遷移（自身のプロフィール画面へは左のProfileボタンからでも可能）
・admin2アカウントのプロフィール画面
・リクエストユーザーであるadmin1はまだadmin2をフォローしていないためボタンはFollow
<img width="1114" alt="プロフィール画面1" src="https://user-images.githubusercontent.com/81793599/133078362-bf6b4c51-7ceb-462e-88ba-465a6e4ee30a.PNG">

ユーザープロフィール画面２
・admin1がadmin2をフォローするとボタンはFollowingとなる
・admin2のFollowersが１となる
<img width="1113" alt="プロフィール画面2" src="https://user-images.githubusercontent.com/81793599/133078694-8b6cfe2e-9ff1-4b86-bf34-511d8a4d06bd.PNG">

ユーザープロフィール画面３
・admin1はadmin2をフォローしている為、admin1のプロフィールページではFollowingsが１となる
・今回のログインユーザーであるadmin1は自分自身をフォローすることはできない為、フォローボタンは表示されない
<img width="1112" alt="プロフィール画面3" src="https://user-images.githubusercontent.com/81793599/133079103-718187db-473f-4a67-877e-a31ff5fa277e.PNG">

フォローユーザー一覧画面
・ユーザープロフィール画面のFollowingsをクリックで遷移
・以下はadmin1のフォローユーザー一覧
<img width="1113" alt="Following画面" src="https://user-images.githubusercontent.com/81793599/133079841-4edf25c8-6dbd-45bc-8348-bebf553ef3e6.PNG">

フォロワー一覧画面
・ユーザープロフィール画面のFollowersをクリックで遷移
・以下はadmin2のフォロワー一覧
<img width="1114" alt="Follower画面" src="https://user-images.githubusercontent.com/81793599/133079634-9e66f381-0688-4651-9b4e-1f346cbb08f1.PNG">

2021-09-13 12:14 UTC, yusukekaneko commented on apps/users/views.py
> +        elif following in follower[0].following.all():
修正しました。

2021-09-13 13:19 UTC, Atiisann commented on apps/tweet/urls.py
> +"""
わかりにくいレビューしてすいません🙇‍♂️
docstringにした理由はありますか？？

不要であれば消してください

2021-09-13 13:23 UTC, Atiisann commented on apps/users/views.py
> +class FollowInUserProfile(FollowBase):
template返してる部分で`View`のついてないのあるので修正依頼しようとしましたが、
修正されてる最高です！！👍

2021-09-13 13:30 UTC, yusukekaneko commented on apps/tweet/urls.py
> +"""
消しました。

2021-09-13 13:32 UTC, Atiisann commented
LGTM!!

2021-09-16 08:09 UTC, fumiharun11 commented on apps/users/urls.py
> +    path('follow/<int:pk>', views.FollowInUserProfile.as_view(), name='follow_in_profile'),
とても細かいけど`<str:username>`の群がまとまっていると読みやすいので、これは1行上に差し込まれていると良いかな

2021-09-16 08:09 UTC, fumiharun11 commented on apps/users/views.py
> +      context['followers_list'] = User.objects.get(username=self.kwargs["username"]).following.all()
存在しない`username`をpathに含んでリクエストが送信された場合の考慮は出来ていますか？

2021-09-16 08:09 UTC, fumiharun11 commented on apps/users/models.py
> +    following = models.ManyToManyField(User, related_name='following', blank=True)
`followee`という命名の方が自然な気がするけど`following`の方が良い？

2021-09-16 08:09 UTC, fumiharun11 commented on apps/tweet/tests.py
> +        time.sleep(0.3)
エラーの原因は`tweet1`と`tweet2`の生成タイムスタンプが想定と逆の順序になっていたとのことだけど、その時の状況を再現させてレコード生成のタイムスタンプをログに出力させることって可能かな？
順番が異なっていた原因のエビデンスを示してもらえると、本当にこの解決策が自然なのかコメントしやすくなるので提出をお願いしたいです。

2021-09-16 08:57 UTC, yusukekaneko commented on apps/users/urls.py
> +    path('follow/<int:pk>', views.FollowInUserProfile.as_view(), name='follow_in_profile'),
修正しました。

2021-09-16 08:59 UTC, yusukekaneko commented on apps/users/views.py
> +      context['followers_list'] = User.objects.get(username=self.kwargs["username"]).following.all()
Profile周りも含めて修正しました。

2021-09-16 09:02 UTC, yusukekaneko commented on apps/tweet/tests.py
> +        time.sleep(0.3)
以下のような状況です。
<img width="741" alt="テストログ" src="https://user-images.githubusercontent.com/81793599/133583516-23f6453e-62ef-4cea-8eab-98c6b0bbf5e1.PNG">

2021-09-16 09:02 UTC, yusukekaneko commented on apps/tweet/tests.py
> +        time.sleep(0.3)
以下のような状況です。

<img width="741" alt="テストログ" src="https://user-images.githubusercontent.com/81793599/133583643-ac852d97-8488-417e-b999-fc9b70dab76f.PNG">

2021-09-16 09:06 UTC, yusukekaneko commented on apps/users/models.py
> +    following = models.ManyToManyField(User, related_name='following', blank=True)
具体的にどの部分でしょうか？（related_nameの方でしょうか？）

2021-09-16 09:35 UTC, yusukekaneko commented on apps/users/models.py
> +    following = models.ManyToManyField(User, related_name='following', blank=True)
修正しました。
ちなみにrelated_name方を修正したのですが、その認識で合ってますでしょうか？

2021-09-17 02:41 UTC, fumiharun11 commented on apps/tweet/tests.py
> +        time.sleep(0.3)
タイムスタンプが同時刻の場合にQuerySetの順序に冪等性がないことで生じる問題だね。
今回は作成日時が明らかに同時刻でないレコードに対してテストを実施するフローを想定していると思うのでこちらの対応でも問題はないと思います。

2021-09-17 02:51 UTC, fumiharun11 commented on apps/users/models.py
> +    following = models.ManyToManyField(User, related_name='following', blank=True)
説明不足で申し訳ない！
ここでの指摘はフィールド(カラム)名についてでした。SNSで見るフォロワー/フォローはfollower/followeeという名称に対応するので。
[参考](https://e-words.jp/w/%E3%83%95%E3%82%A9%E3%83%AD%E3%83%BC.html)
また、related_nameの修正については良いと思います:+1:

2021-09-17 03:12 UTC, fumiharun11 commented on apps/users/views.py
> +      return render(request, 'users/profile.html', {'user_data':user_data, 'post_data':post_data, 'following_count':following_count, 'followers_count':followers_count ,'request_user_following_list':r
第三引数について、他の箇所で変数`context`として渡しているならここも`context`に格納して渡してあげると統一感あって可読性上がるかな？
第三者に読まれることを意識して書いてみると気をつけやすくなるかも！

2021-09-17 03:58 UTC, yusukekaneko commented on apps/users/models.py
> +    following = models.ManyToManyField(User, related_name='following', blank=True)
修正しました。カラム名の変更に伴い、views.pyやtest.pyも併せて修正しました。

2021-09-17 03:58 UTC, yusukekaneko commented on apps/users/views.py
> +      return render(request, 'users/profile.html', {'user_data':user_data, 'post_data':post_data, 'following_count':following_count, 'followers_count':followers_count ,'request_user_following_list':r
修正しました。

2021-09-17 04:01 UTC, yusukekaneko commented on apps/tweet/tests.py
> +        time.sleep(0.3)
当初の対応で問題ないとのことなので、改めてtime.sleepを利用してツイートの順番を確定させるようにしました。

2021-09-17 05:12 UTC, fumiharun11 approved these changes
LGTM

2021-09-17 05:12 UTC, merged