お気に入り機能の実装
yusukekaneko/twitter_clone pull request #4
Opened 2021-09-19 08:20 UTC by yusukekaneko

お気に入り機能を実装致しました。
ご確認の程よろしくお願い致します。

2021-09-20 01:37 UTC, Atiisann requested changes
確認おねがいします

2021-09-20 01:37 UTC, TonkyH commented on apps/tweet/tests.py
> +import json
他がアルファベット順になっているので、
ここもアルファベット順のほうが綺麗かもしれません

2021-09-20 01:37 UTC, Atiisann commented on apps/tweet/views.py
> +               liked_list.append(post.pk)
for文の中で`filter`使うとクエリが大量に発行されるため、パフォーマンス的によくないです、、
なんとか修正してほしいです。

自分がいいねしたpost情報をlistで保持したいために、`liked_list`が必要でしたら
`Like`を`request.user`で検索してくる方針ではダメでしょうか？ 
 さらに、`values_list()`を使えば、`post.pk`だけを保持させることも可能かと思います

- https://docs.djangoproject.com/en/3.2/ref/models/querysets/#values-list

また、`liked_list`のなかに`Likeオブジェクト`ではなく`post.pk`の情報を持たせているなら、`liked_post_pk_list`
などの方が混乱しにくいと思います！

2021-09-20 01:37 UTC, Atiisann commented on apps/tweet/views.py
> +               liked_post_list.append(post)
パフォーマンス的にまずそうなので
同様に修正

2021-09-20 01:37 UTC, Atiisann commented on apps/tweet/views.py
> +         like.create(user=request.user, post=post)
ぱっと見、`get_or_create`使えそう

- https://docs.djangoproject.com/en/3.2/ref/models/querysets/#get-or-create

2021-09-20 01:37 UTC, Atiisann commented on apps/tweet/views.py
> +         like.delete()
これじゃダメだっけ
```python
like = Like.objects.filter(user=self.request.user, post=post)
if like:
    like.delete()
```

それか、セイウチ演算子使えるなら(python3.8から使えたはず)
これでもいける気がする
```python
if like := Like.objects.filter(user=self.request.user, post=post)
    like.delete()
```

2021-09-20 01:37 UTC, Atiisann commented on apps/users/views.py
> +               liked_list.append(post.pk)
パフォーマンス的にまずそうなので
同様に修正

2021-09-20 01:44 UTC, Atiisann commented
テストが通ったスクショください🙇‍♂️
もし、テストが書けてなかったら動作確認したスクショください！！

2021-09-20 02:50 UTC, yusukekaneko commented
users app test
<img width="430" alt="users test" src="https://user-images.githubusercontent.com/81793599/133952868-62101478-00be-4950-99fd-08eb78e904b7.PNG">

tweet app test
<img width="433" alt="tweet test" src="https://user-images.githubusercontent.com/81793599/133952876-ed11b073-e845-47c8-bf33-c71d21352119.PNG">

2021-09-20 02:53 UTC, yusukekaneko commented on apps/tweet/tests.py
> +import json
修正しました。

2021-09-20 02:54 UTC, yusukekaneko commented on apps/tweet/views.py
> +               liked_list.append(post.pk)
修正しました。

2021-09-20 02:54 UTC, yusukekaneko commented on apps/tweet/views.py
> +               liked_post_list.append(post)
修正しました。

2021-09-20 02:54 UTC, yusukekaneko commented on apps/tweet/views.py
> +         like.create(user=request.user, post=post)
修正しました。

2021-09-20 02:54 UTC, yusukekaneko commented on apps/tweet/views.py
> +         like.delete()
修正しました。

2021-09-20 02:54 UTC, yusukekaneko commented on apps/users/views.py
> +               liked_list.append(post.pk)
修正しました。

2021-09-20 03:06 UTC, Atiisann commented
LGTM！！

2021-09-22 02:41 UTC, fumiharun11 approved these changes
LGTM

2021-09-22 02:41 UTC, merged